name: SDFormat Build & Test

on:
  push:
    branches:
      - feature/python-packaging
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest 
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name : Adding GPG key
        run: |
          sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
          wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
          sudo apt update

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y install \
            $(sort -u $(find . -iname 'packages-'`lsb_release -cs`'.apt' -o -iname 'packages.apt' | tr '\n' ' '))

      - name: Build & Install SDFormat
        run: |
          mkdir -p build
          pushd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/python_packaging
          make -j $(nproc)
          popd
          cp -r build/lib/* sdformat15/

      - name: Create Python Package
        run: |
            pip install setuptools wheel
            python3 setup.py sdist bdist_wheel
            zip -r sdformat15.zip dist/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: sdformat15
            path: sdformat15.zip

        

      - name: Get Version Tag
        id: version_tag
        run: echo "tag=v$(date +'%Y.%m.%d')-build-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
  
      - name: Create release
        id: SDFormat_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version_tag.outputs.tag }}
        run: |
          gh release create "${{ steps.version_tag.outputs.tag }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="SDFormat Python Library - ${{ steps.version_tag.outputs.tag }}" \
              --generate-notes


      - name: Upload Binary to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{steps.version_tag.outputs.tag }}" \
              sdformat15.zip 


          
